version: '2'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  ignite:
    image: apacheignite/ignite:2.3.0
    environment:
      JVM_OPTS: -XX:+UseG1GC
      OPTION_LIBS: ignite-zookeeper,ignite-rest-http
      CONFIG_URI: /src/ignite-zookeeper.xml
    links:
      - zookeeper:zk.zookeeper.rancher.internal
    volumes:
      - ./:/src
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
  source-cloner:
    image: minio/mc
    command: mirror --overwrite --watch --remove /source/ /data/source
    volumes:
      - ./tmp/worker:/data
      - ./tmp/remote_source:/source
  redis-ui:
    image: ficusio/redis-commander:latest
    command:  --redis-host redis --redis-port 6379
    links:
      - redis:redis
    ports:
      - 8081:8081
#  worker:
#    build: ./
#    command:
#      aiotasks
#      -vvvv
#      worker
#      -A
#      worker/app
#    links:
#      - redis:redis
#      - zookeeper:zookeeper
#      - ignite:ignite