version: '2'
services:
  datanode:
    privileged: true
    image: negash/rancher-saas:latest
    environment:
      NATS_DSN: nats://nats:4222
      SERVICE_NAME: mysql
      DATA_SOURCE_FREEZE_TIME: '25'
      SERVICE_ENV_MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      SERVICE_PORT: 3306/tcp
      SERVICE_IMAGE: mariadb:5.5
      SERVICE_VOLUME: /var/lib/mysql
      SERVICE_CMD: mysqld --defaults-file=/var/lib/mysql/my.cnf --innodb_log_buffer_size=256M --innodb_log_file_size=512M --max_connections=2000 --character-set-server=utf8
      SERVICE_ENV_MYSQL_DATABASE: mysq_database
      USE_RANCHER: '1'
    stdin_open: true
    links:
    - nats:nats
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /mnt:/mnt:shared
    - /mysql_source_data_from_nfs:/source
    tty: true
    pid: host
    command:
    - python3
    - -m
    - japronto
    - data.app
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: no=saas
      io.rancher.scheduler.global: 'true'
  delivery:
    image: negash/rancher-saas:latest
    environment:
      NATS_DSN: nats://nats:4222
      SERVICE_NAME: mysql
    stdin_open: true
    links:
    - nats:nats
    tty: true
    command:
    - python3
    - -m
    - japronto
    - delivery.app
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.hostname_override: container_name
  nats-1:
    image: nats
    command: -p 4222 --http_port 8080 -cluster nats://0.0.0.0:5222 -routes nats://nats-2:5222,nats://nats-3:5222 -D
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1mb
  nats-2:
    image: nats
    command: -p 4222 --http_port 8080 -cluster nats://0.0.0.0:5222 -routes nats://nats-1:5222,nats://nats-3:5222 -D
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1mb
  nats-3:
    image: nats
    command: -p 4222 --http_port 8080 -cluster nats://0.0.0.0:5222 -routes nats://nats-1:5222,nats://nats-2:5222 -D
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1mb
  nats:
    image: nats
    links:
      - nats-1:nats-1
      - nats-2:nats-2
      - nats-3:nats-3
    command: -p 4222 --http_port 8080 -cluster nats://0.0.0.0:5222 -routes nats://nats-1:5222,nats://nats-2:5222,nats://nats-3:5222 -D
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1mb
