version: '2'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  ignite:
    image: apacheignite/ignite
    environment:
      OPTION_LIBS: ignite-rest-http
      CONFIG_URI: https://raw.githubusercontent.com/apache/ignite/master/examples/config/example-cache.xml
    ports:
      - 8082:8080
      - 10800:10800
      - 11211:11211
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
  source-cloner:
    image: minio/mc
    command: mirror --overwrite --remove /source/ /data/source
    volumes:
      - ./tmp/worker:/data
      - ./tmp/remote_source:/source
  redis-ui:
    image: ficusio/redis-commander:latest
    command:  --redis-host redis --redis-port 6379
    links:
      - redis:redis
    ports:
      - 8081:8081
#  worker:
#    build: ./
#    command:
#      aiotasks
#      -vvvv
#      worker
#      -A
#      worker/app
#    links:
#      - redis:redis
#      - zookeeper:zookeeper
#      - ignite:ignite