version: '2'
services:
  source-cloner:
    image: minio/mc
    command: mirror --overwrite --remove /data/ /source
    volumes:
      - ./tmp/worker:/data
      - ./tmp/remote_source:/source
#  ignite:
#    image: apacheignite/ignite:2.3.0
#    environment:
#      JVM_OPTS: -XX:+UseG1GC
#      OPTION_LIBS: ignite-zookeeper,ignite-rest-http
#      CONFIG_URI: /src/ignite-zookeeper.xml
#    links:
#      - zookeeper:zk.zookeeper.rancher.internal
#    volumes:
#      - ./:/src
#  zookeeper:
#    image: zookeeper
#    ports:
#      - 2181:2181
#  nats-1:
#    image: nats
#    command: -p 4222 --http_port 8080 -cluster nats://0.0.0.0:5222 -routes nats://nats-2:5222,nats://nats-3:5222 -D
#    ports:
#      - 8080
#  nats-2:
#    image: nats
#    command: -p 4222 --http_port 8080 -cluster nats://0.0.0.0:5222 -routes nats://nats-1:5222,nats://nats-3:5222 -D
#    ports:
#      - 8080
#  nats-3:
#    image: nats
#    command: -p 4222 --http_port 8080 -cluster nats://0.0.0.0:5222 -routes nats://nats-1:5222,nats://nats-2:5222 -D
#    ports:
#      - 8080
#  nats:
#    image: nats
#    command: -p 4222 --http_port 8080 -cluster nats://0.0.0.0:5222 -routes nats://nats-1:5222,nats://nats-2:5222,nats://nats-3:5222 -D
#    ports:
#      - 8080
  data:
    build: .
    image: negash/rancher-saas:zfs
    privileged: true
    pid: host
    stdin_open: true
    tty: true
    command: python3 -m japronto data.app --reload
    working_dir: /opt/project
    ports:
      - 8000:8080
    volumes:
      - /home/negash/Dropbox/PycharmProjects/rancher-saas:/opt/project
      - /data-source:/source
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt:/mnt:shared
    environment:
      DEBUG: 1
      USE_IP_ADDR: 192.168.122.23
  delivery:
    build: .
    image: negash/rancher-saas:zfs
    stdin_open: true
    tty: true
    command: python3 -m japronto delivery.app --reload
    working_dir: /opt/project
    ports:
      - 8080:8080
    volumes:
      - /home/negash/Dropbox/PycharmProjects/rancher-saas:/opt/project
  nats-1:
    image: nats
    command: -p 4222 --http_port 8080 -cluster nats://0.0.0.0:5222 -routes nats://nats-2:5222,nats://nats-3:5222 -D
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1mb
  nats-2:
    image: nats
    command: -p 4222 --http_port 8080 -cluster nats://0.0.0.0:5222 -routes nats://nats-1:5222,nats://nats-3:5222 -D
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1mb
  nats-3:
    image: nats
    command: -p 4222 --http_port 8080 -cluster nats://0.0.0.0:5222 -routes nats://nats-1:5222,nats://nats-2:5222 -D
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1mb
  nats:
    image: nats
    links:
      - nats-1:nats-1
      - nats-2:nats-2
      - nats-3:nats-3
    command: -p 4222 --http_port 8080 -cluster nats://0.0.0.0:5222 -routes nats://nats-1:5222,nats://nats-2:5222,nats://nats-3:5222 -D
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1mb